name: safedose
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  mobile_scanner: ^7.1.4
  cloud_firestore: ^6.1.1
  firebase_core: ^4.3.0
  google_generative_ai: ^0.4.7
  intl: ^0.20.2
  firebase_auth: ^6.1.3
  google_sign_in: ^7.2.0
  camera: ^0.11.2+1
  shared_preferences: ^2.3.5
  flutter_tts: ^4.2.5
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
